// import "./globals.css";
// import Header3 from "../Components/Header/Header3";
// import Footer from "../Components/Footer/Footer";

// export const metadata = {
//   title: "My App",
//   description: "Generated by Next.js",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body>
//         <Header3 />
//         {children}
//         <Footer />
//       </body>
//     </html>
//   );
// }
